### ISSUE TITLE
Add a way of disabling multicast receive

### ISSUE THREAD

**Issue by ampledata** [snstac/pytak#28]
Yes, I realize I just added multicast receive, but running more than one multicast client on the same host is blocked.

The use case is: I want to run multiple multicast senders on one machine.

**Comment by PeterQFR** [comment]
Ah is it? I just tried two multicast clients on the one machine and it didn't work. I also tried to run to TLS clients on the one machine, and as soon as I launched the second, the first stopped transmitting and receiving. The use case was for debugging and testing.

**Comment by ampledata** [comment]
@PeterQFR add "+ro" do your URL string, for example, COT_URL=udp+ro://...

**Comment by PeterQFR** [comment]
thanks. I am getting `OSError: address already in use` when starting another pytak client ...  not on the same machine. 
Both Clients are using udp+ro://239.2.3.1:6969 but also triggers if just using udp. 

The first client will connect fine. That system is on a standard LAN network. The second machine is using a shared network connection to the first. 

I'm not really sure of the canonical topologies when using udp multicast.  I think they always require a router, but can I configure a machine acting as a wireless AP to perform udp multicast to connected clients?

**Comment by ampledata** [comment]
Hey @PeterQFR, that's my bad, it should be `+wo`, as in 'Write-only'.

As for Multicast on WiFi: It /should/ work on most routers/APs out of the box. To tranverse the network, ensure 'multicast routing' or 'multicast snoop' or 'igmp' are turned on (in the case of my COTS TP-Link AP: yes, IGMP was turned on by default.
