### ISSUE TITLE
PYTAK_TLS_CLIENT_KEY in Docs is actually in PYTAK_TLS_CLIENT_PASSWORD

### ISSUE THREAD

**Issue by SamKiley** [snstac/pytak#42]
PYTAK_TLS_CLIENT_KEY in Docs is actually in PYTAK_TLS_CLIENT_PASSWORD. I assume the Docs are out of date, but just wanted to point this one out. I followed the basic installation instructions for Pytak shown in the Docs.

**Comment by ampledata** [comment]
Hey @SamKiley thanks for the report.

Those two config parameters are different, although the later, `PYTAK_TLS_CLIENT_PASSWORD` isn't actually included in the documentation. 

For reference:

`PYTAK_TLS_CLIENT_KEY`: Path to the Client Key.

`PYTAK_TLS_CLIENT_PASSWORD`: PKCS#12 password.

**Comment by PeterQFR** [comment]
Hey does this mean we can use p12 certificates and key directly or is there still a requirement to convert to a .pem format?

**Comment by ampledata** [comment]
@PeterQFR yes, datapackages (user.zip, et al) are supported. See PREF_PACKAGE at https://pytak.readthedocs.io/en/latest/configuration/

**Comment by davesauce14** [comment]
> @PeterQFR yes, datapackages (user.zip, et al) are supported. See PREF_PACKAGE at https://pytak.readthedocs.io/en/latest/configuration/

Hi @ampledata it seems that setting "PREF_PACKAGE" in the config (in send_receive.py example) doesnt work.
`read_pref_package` seems to not get called.

Example usage:
`config["mycottool"] = {"PREF_PACKAGE": "test.zip"}`
