### ISSUE TITLE
Nonexistant Civ icons for certain categories

### ISSUE THREAD

**Issue by sniporbob** [snstac/pytak#6]
A General Atomics drone recently flew within ADSB range. ICAO A3C1BE. This is within the Civ ICAO range. However, there is no valid icon type for a civilian affil drone. The affil must be set to mil to have a valid drone icon. The current code results in the standard civ fixed wing icon. Possible solution:

cot_type = f"a-{attitude}-A-M-F-Q"

Either way, Q needs to be capitalized as lowercase Q was not recognized by WinTAK.

**Comment by spineaker-actual** [comment]
Recommend any civil icao address range with the drone DO260B or GDL90 emitter category be {attitude}=neutral and as listed above. 
example: a-n-A-M-F-Q
This will present a green square batwing drone 2525 B icon. And differentiate from MIl drones.
